language: java

dist: trusty

jdk: openjdk11

before_install:
  - chmod +x gradlew

install:
  - ./gradlew build -s

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - markus.oley@googlemail.com
